// default package
// Generated May 24, 2016 7:12:57 PM by Hibernate Tools 5.1.0.Alpha3
package com.jspwebapps.DatabasePojos;

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer empCityId;
	private String cityName;
	private int cityZip;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public City() {
	}

	public City(String cityName, int cityZip) {
		this.cityName = cityName;
		this.cityZip = cityZip;
	}

	public City(String cityName, int cityZip, Set<Employee> employees) {
		this.cityName = cityName;
		this.cityZip = cityZip;
		this.employees = employees;
	}

	public Integer getEmpCityId() {
		return this.empCityId;
	}

	public void setEmpCityId(Integer empCityId) {
		this.empCityId = empCityId;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public int getCityZip() {
		return this.cityZip;
	}

	public void setCityZip(int cityZip) {
		this.cityZip = cityZip;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
