// default package
// Generated May 24, 2016 7:12:57 PM by Hibernate Tools 5.1.0.Alpha3
package com.jspwebapps.DatabasePojos;
import java.util.HashSet;
import java.util.Set;

/**
 * Position generated by hbm2java
 */
public class Position implements java.io.Serializable {

	private Integer positionId;
	private String positionName;
	private int baseSalary;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Position() {
	}

	public Position(String positionName, int baseSalary) {
		this.positionName = positionName;
		this.baseSalary = baseSalary;
	}

	public Position(String positionName, int baseSalary, Set<Employee> employees) {
		this.positionName = positionName;
		this.baseSalary = baseSalary;
		this.employees = employees;
	}

	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	public String getPositionName() {
		return this.positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	public int getBaseSalary() {
		return this.baseSalary;
	}

	public void setBaseSalary(int baseSalary) {
		this.baseSalary = baseSalary;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
