// default package
// Generated May 24, 2016 1:07:55 PM by Hibernate Tools 5.1.0.Alpha3

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer empId;
	private City city;
	private Department department;
	private Position position;
	private String empFname;
	private String empLastName;
	private int empPhone;
	private String empLastName_1;

	public Employee() {
	}

	public Employee(City city, Department department, Position position, String empFname, String empLastName,
			int empPhone) {
		this.city = city;
		this.department = department;
		this.position = position;
		this.empFname = empFname;
		this.empLastName = empLastName;
		this.empPhone = empPhone;
	}

	public Employee(City city, Department department, Position position, String empFname, String empLastName,
			int empPhone, String empLastName_1) {
		this.city = city;
		this.department = department;
		this.position = position;
		this.empFname = empFname;
		this.empLastName = empLastName;
		this.empPhone = empPhone;
		this.empLastName_1 = empLastName_1;
	}

	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public String getEmpFname() {
		return this.empFname;
	}

	public void setEmpFname(String empFname) {
		this.empFname = empFname;
	}

	public String getEmpLastName() {
		return this.empLastName;
	}

	public void setEmpLastName(String empLastName) {
		this.empLastName = empLastName;
	}

	public int getEmpPhone() {
		return this.empPhone;
	}

	public void setEmpPhone(int empPhone) {
		this.empPhone = empPhone;
	}

	public String getEmpLastName_1() {
		return this.empLastName_1;
	}

	public void setEmpLastName_1(String empLastName_1) {
		this.empLastName_1 = empLastName_1;
	}

}
