// default package
// Generated May 24, 2016 1:07:55 PM by Hibernate Tools 5.1.0.Alpha3

import java.util.HashSet;
import java.util.Set;

/**
 * Position generated by hbm2java
 */
public class Position implements java.io.Serializable {

	private Integer positionId;
	private String positionName;
	private int baseSalary;
	private Set employees = new HashSet(0);

	public Position() {
	}

	public Position(String positionName, int baseSalary) {
		this.positionName = positionName;
		this.baseSalary = baseSalary;
	}

	public Position(String positionName, int baseSalary, Set employees) {
		this.positionName = positionName;
		this.baseSalary = baseSalary;
		this.employees = employees;
	}

	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	public String getPositionName() {
		return this.positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	public int getBaseSalary() {
		return this.baseSalary;
	}

	public void setBaseSalary(int baseSalary) {
		this.baseSalary = baseSalary;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
